# Generated by Django 4.0.5 on 2022-06-22 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0002_alter_myuser_user_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='address',
        ),
    ]
