# Generated by Django 4.0.5 on 2022-06-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0003_remove_myuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='password2',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
