# Generated by Django 4.0.5 on 2022-06-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0004_myuser_password2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='password2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
