# Generated by Django 4.0.5 on 2022-06-23 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0005_alter_myuser_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='password2',
        ),
    ]
